Window.width: 800
Window.height: 600
Window.title: Model Viewer
Window.fullscreen: false
UI.isCreditsPanelOpen: false
UI.isLightPanelOpen: false
UI.isMaterialPanelOpen: false
UI.isShaderPanelOpen: false