Window.width: 800
Window.height: 600
Window.title: Model Viewer
Window.fullscreen: false
UI.isCreditsPanelOpen: false
UI.isLightPanelOpen: true
UI.isMaterialPanelOpen: true
UI.isShaderPanelOpen: false